### ISSUE TITLE
Very large serie cause Stack Overflow : proposed fix

### ISSUE THREAD

**Issue by PeterVermont** [simogeo/geostats#33]
The min and max methods use this:

`this.stat_min = Math.min.apply(null, this.serie);`

This apparently is recursive because I got this error:
![image](https://cloud.githubusercontent.com/assets/889233/19056567/1011c406-8998-11e6-9cda-8dc27f532b71.png)

My quick and dirty workaround was to replace your min and max functions using d3 min and max functions:

```
    var geoStatsObject = new geostats(allData);
    geoStatsObject.min = function () {
        if (this._nodata())
            return;

        this.stat_min = d3.min(this.serie);

        return this.stat_min;
    };

    geoStatsObject.max = function () {
        if (this._nodata())
            return;

        this.stat_max = d3.max(this.serie);

        return this.stat_max;
    };

```

**Comment by simogeo** [comment]
thanks for reporting, can help other users !

**Comment by mthh** [comment]
Hi,

@PeterVermont about how many elements in a "large serie" are you talking (just by curiosity!)
It isn't really a workaround for this specific issue but when I am dealing with large arrays, I tend to use simple and native JS function like : 
```javascript
function min_array(arr){
  let min = arr[0];
  for(let i = 1, len_i = arr.length; i < len_i; ++i){
    let val = +arr[i];
    if(val && val < min)
       min = val;
  }
  return min;
}
```
which could be used here like `min_array(this.serie)` in place of `d3.min(this.serie)`.
In my (really naive) benchmark if offers some speedup compared to Math.min/max.apply or d3.min/max (well, we are talking about micro-optimization!, but still, its faster and doesn't involve any third party library)

@simogeo As d3.min, the snippet above ignore NaN values while geostats min() method return a NaN value if there is one in the original array. Is it by design ?

**Comment by PeterVermont** [comment]
My serie was ~240k

**Comment by simogeo** [comment]
Sorry for the delay.

Could you please try with the latest geostats version ?  see commit : 9a0b715ee814a891de7f8496ad3ebb32bcc9f4d9

**Comment by PeterVermont** [comment]
I am sorry but working hard on a different project just now.

**Comment by simogeo** [comment]
Please open it again if bug still appears
