### ISSUE TITLE
recommended academic citation for geostats

### ISSUE THREAD

**Issue by scottpez** [simogeo/geostats#55]
Thank you so much for your contribution to the mapping community. I have used geostats in my dissertation work. It works well and efficiently and does exactly what is described. Thank you again for this useful tool.

I am preparing an academic manuscript where I discuss my research and would like to include a proper citation to geostats. I am fine with adding a citation for the software itself and referencing the github page. However, I would like to first ask if geostats was developed for an academic research project, and is there an accompanying manuscript I can cite instead? If not, no problem as I am still happy to cite the github site as I mentioned.

Kind regards,
Scott

**Comment by simogeo** [comment]
Hi @scottpez : thanks for your message.  There is no academic purpose regarding _geostats_ library. Actually, I developed it because I just needed it and there was no similar project at that time.

You will find some information regarding why and how, looking at my original post on (almost 5 years ago) :  
https://gis.stackexchange.com/questions/11106/tiny-js-discretization-library-for-choropleth-representation/11161

What is the academic  project you are working on with _geostats_ ? I'm always curious to know !

Regards
